### ISSUE TITLE
Error in exception trace

### ISSUE THREAD

**Issue by BryanButler** [Nevay/spi#4]
Hello, it would appear as though something is off when building the new V1.0.2 using composer 2.8.1. It appears to be some sort of syntax error resulting from the newer foreach comparison of providers to services in src/Composer/Plugin.php.

I'm going to attempt to use V1.0.1 in the mean time but I figured it wouldn't hurt to ask for guidance / bring this to your attention.

 Install of tbachert/spi failed
In Plugin.php line 99:
                                               
 Exception trace:
  at /builds/mysite/app/vendor/tbachert/spi/src/Composer/Plugin.php:99
 Composer\Autoload\{closure}() at phar:///builds/mysite/composer.phar/vendor/composer/ClassLoader.php:427
 Composer\Autoload\ClassLoader->loadClass() at n/a:n/a
 spl_autoload_call() at n/a:n/a
 class_exists() at phar:///builds/mysite/composer.phar/src/Composer/Plugin/PluginManager.php:293
 Composer\Plugin\PluginManager->registerPackage() at phar:///builds/mysite/composer.phar/src/Composer/Installer/PluginInstaller.php:90
 Composer\Installer\PluginInstaller->Composer\Installer\{closure}() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Internal/FulfilledPromise.php:47
 React\Promise\Internal\FulfilledPromise->then() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:173
 React\Promise\Promise::React\Promise\{closure}() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:221
 React\Promise\Promise->settle() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:286
 React\Promise\Promise::React\Promise\{closure}() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Internal/FulfilledPromise.php:47
 React\Promise\Internal\FulfilledPromise->then() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:180
 React\Promise\Promise::React\Promise\{closure}() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:221
 React\Promise\Promise->settle() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:286
 React\Promise\Promise::React\Promise\{closure}() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Internal/FulfilledPromise.php:47
 React\Promise\Internal\FulfilledPromise->then() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:177
 React\Promise\Promise::React\Promise\{closure}() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:221
 React\Promise\Promise->settle() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:286
 React\Promise\Promise::React\Promise\{closure}() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Internal/FulfilledPromise.php:47
 React\Promise\Internal\FulfilledPromise->then() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:180
 React\Promise\Promise::React\Promise\{closure}() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:221
 React\Promise\Promise->settle() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:286
 React\Promise\Promise::React\Promise\{closure}() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Internal/FulfilledPromise.php:47
 React\Promise\Internal\FulfilledPromise->then() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:180
 React\Promise\Promise::React\Promise\{closure}() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:221
 React\Promise\Promise->settle() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:286
 React\Promise\Promise::React\Promise\{closure}() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Internal/FulfilledPromise.php:47
 React\Promise\Internal\FulfilledPromise->then() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:180
 React\Promise\Promise::React\Promise\{closure}() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:221
 React\Promise\Promise->settle() at phar:///builds/mysite/composer.phar/vendor/react/promise/src/Promise.php:286
 React\Promise\Promise::React\Promise\{closure}() at n/a:n/a
 call_user_func() at phar:///builds/mysite/composer.phar/src/Composer/Util/ProcessExecutor.php:367
 Composer\Util\ProcessExecutor->countActiveJobs() at phar:///builds/mysite/composer.phar/src/Composer/Util/Loop.php:90
 Composer\Util\Loop->wait() at phar:///builds/mysite/composer.phar/src/Composer/Installer/InstallationManager.php:433
 Composer\Installer\InstallationManager->waitOnPromises() at phar:///builds/mysite/composer.phar/src/Composer/Installer/InstallationManager.php:408
 Composer\Installer\InstallationManager->executeBatch() at phar:///builds/mysite/composer.phar/src/Composer/Installer/InstallationManager.php:322
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar:///builds/mysite/composer.phar/src/Composer/Installer/InstallationManager.php:221
 Composer\Installer\InstallationManager->execute() at phar:///builds/mysite/composer.phar/src/Composer/Installer.php:839
 Composer\Installer->doInstall() at phar:///builds/mysite/composer.phar/src/Composer/Installer.php:300
 Composer\Installer->run() at phar:///builds/mysite/composer.phar/src/Composer/Command/InstallCommand.php:147
 Composer\Command\InstallCommand->execute() at phar:///builds/mysite/composer.phar/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///builds/mysite/composer.phar/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar:///builds/mysite/composer.phar/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///builds/mysite/composer.phar/src/Composer/Console/Application.php:407
 Composer\Console\Application->doRun() at phar:///builds/mysite/composer.phar/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///builds/mysite/composer.phar/src/Composer/Console/Application.php:147
 Composer\Console\Application->run() at phar:///builds/mysite/composer.phar/bin/composer:93
 require() at /builds/mysite/composer.phar:29
install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

**Comment by Nevay** [comment]
Hello, can you provide a `composer.json` that triggers the error / which PHP version are you using?
(Based on the stacktrace I would assume that composer ran with PHP7.4; this package requires PHP ^8.1.)

**Comment by BryanButler** [comment]
Incredible work fella. Despite the server running 8.1 and docker running 8.1 locally. It would appear as though my automated build process was pulling a 7.4 image. Thank you much for the resolution.
